# Generated by Django 4.1.10 on 2023-08-08 20:01

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DentalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenant_name', models.CharField(max_length=50, verbose_name='Nome do convênio')),
                ('card_number', models.CharField(max_length=50, verbose_name='Número do cartão')),
                ('plan_name', models.CharField(max_length=50, verbose_name='Nome do plano')),
                ('user_type', models.CharField(choices=[(home.models.UserTypeEnum['HOLDER'], 'Titular'), (home.models.UserTypeEnum['DEPENDENT'], 'Dependente')], max_length=50, verbose_name='Tipo de usuário')),
                ('holder_name', models.CharField(max_length=50, verbose_name='Nome do titular')),
                ('ans_code', models.CharField(max_length=50, verbose_name='Código da ANS')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='HowKnowAboutClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('id_number', models.CharField(max_length=50, verbose_name='RG')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Telefone')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('sex', models.CharField(choices=[(home.models.SexEnum['M'], 'Masculino'), (home.models.SexEnum['F'], 'Feminino'), (home.models.SexEnum['TM'], 'Trans Masculino'), (home.models.SexEnum['TF'], 'Trans Feminino'), (home.models.SexEnum['O'], 'Outro')], max_length=50, verbose_name='Sexo')),
                ('address', models.CharField(max_length=50, verbose_name='Endereço')),
                ('how_know_about_clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.howknowaboutclinic', verbose_name='Como conheceu a clínica')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('description', models.CharField(max_length=50, verbose_name='Descrição')),
                ('status', models.CharField(choices=[(home.models.TransactionStatusEnum['IN'], 'Entrada'), (home.models.TransactionStatusEnum['OUT'], 'Saída')], max_length=50, verbose_name='Status')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('accumulated', models.FloatField(verbose_name='Acumulado')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_transactions', to='home.patient', verbose_name='Paciente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_transactions', to='home.product', verbose_name='Produto')),
            ],
        ),
    ]
